spring.application.name=EmployeeManagement

spring.profiles.active=test

logging.level.root=INFO
logging.level.com.example.employeemanagement.controller=DEBUG
logging.level.com.example.employeemanagement.service=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%level] %logger{36} - %msg%n
